require "user.impatient"
require "user.options"
require "user.utils"
require "user.keymaps"
require "user.plugins"
require "user.lsp"
require "user.colorscheme"
require "user.telescope"
require "user.nvim-tree"
require "user.treesitter"
require "user.cmp"
require "user.lualine"
require "user.gitsigns"
--require "user.winbar" needs NAVIC highlight groups
require "user.indentblankline"
require "user.todo-comments"
require "user.comment"
require "user.autopairs"
require "user.neoscroll"
require "user.renamer"
require "user.functions"
require "user.which-key"
-- TODO: 1. Get null-ls formatting working
-- TODO: 2. Fix Colors (Highlight groups for signs, adjust bg color)

