require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.utils"
require "user.colorscheme"
require "user.nvim-tree"
require "user.alpha"
require "user.notify"
require "user.plugins"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.ts-context"
require "user.cmp"
require "user.lualine"
require "user.gitsigns"
require "user.toggleterm"
require "user.illuminate"
--require "user.winbar" needs NAVIC highlight groups
require "user.indentblankline"
require "user.todo-comments"
require "user.comment"
require "user.autopairs"
require "user.neoscroll"
require "user.renamer"
require "user.functions"
require "user.which-key"
-- TODO: 1. Get CodeRunner set up working (toggle term?)
