return {
    { "<leader>S", group = "Symbols", nowait = true, remap = false },

    { "<leader>SS", group = "Superscripts", nowait = true, remap = false },
    { "<leader>SS+", ":normal a⁺<Esc>", desc = "Insert superscript +", nowait = true, remap = false },
    { "<leader>SS-", ":normal a⁻<Esc>", desc = "Insert superscript -", nowait = true, remap = false },
    { "<leader>SS0", ":normal a⁰<Esc>", desc = "Insert superscript 0", nowait = true, remap = false },
    { "<leader>SS1", ":normal a¹<Esc>", desc = "Insert superscript 1", nowait = true, remap = false },
    { "<leader>SS2", ":normal a²<Esc>", desc = "Insert superscript 2", nowait = true, remap = false },
    { "<leader>SS3", ":normal a³<Esc>", desc = "Insert superscript 3", nowait = true, remap = false },
    { "<leader>SS4", ":normal a⁴<Esc>", desc = "Insert superscript 4", nowait = true, remap = false },
    { "<leader>SS5", ":normal a⁵<Esc>", desc = "Insert superscript 5", nowait = true, remap = false },
    { "<leader>SS6", ":normal a⁶<Esc>", desc = "Insert superscript 6", nowait = true, remap = false },
    { "<leader>SS7", ":normal a⁷<Esc>", desc = "Insert superscript 7", nowait = true, remap = false },
    { "<leader>SS8", ":normal a⁸<Esc>", desc = "Insert superscript 8", nowait = true, remap = false },
    { "<leader>SS9", ":normal a⁹<Esc>", desc = "Insert superscript 9", nowait = true, remap = false },
    { "<leader>Sc", ":normal a●<Esc>", desc = "Insert ●", nowait = true, remap = false },
    { "<leader>Sd", ":normal a°<Esc>", desc = "Insert °", nowait = true, remap = false },
    { "<leader>Sf", "<cmd>IconPickerNormal<cr>", desc = "Find", nowait = true, remap = false },

    { "<leader>Sg", group = "Greek Symbols", nowait = true, remap = false },
    { "<leader>SgS", ":normal aΣ<Esc>", desc = "Insert Σ", nowait = true, remap = false },
    { "<leader>Sga", ":normal aα<Esc>", desc = "Insert α", nowait = true, remap = false },
    { "<leader>Sgb", ":normal aβ<Esc>", desc = "Insert β", nowait = true, remap = false },
    { "<leader>Sgc", ":normal aχ<Esc>", desc = "Insert χ", nowait = true, remap = false },
    { "<leader>Sgd", ":normal aδ<Esc>", desc = "Insert δ", nowait = true, remap = false },
    { "<leader>Sge", ":normal aε<Esc>", desc = "Insert ε", nowait = true, remap = false },
    { "<leader>Sgf", ":normal aφ<Esc>", desc = "Insert φ", nowait = true, remap = false },
    { "<leader>Sgg", ":normal aγ<Esc>", desc = "Insert γ", nowait = true, remap = false },
    { "<leader>Sgh", ":normal aη<Esc>", desc = "Insert η", nowait = true, remap = false },
    { "<leader>Sgi", ":normal aι<Esc>", desc = "Insert ι", nowait = true, remap = false },
    { "<leader>Sgk", ":normal aκ<Esc>", desc = "Insert κ", nowait = true, remap = false },
    { "<leader>Sgl", ":normal aλ<Esc>", desc = "Insert λ", nowait = true, remap = false },
    { "<leader>Sgm", ":normal aµ<Esc>", desc = "Insert µ", nowait = true, remap = false },
    { "<leader>Sgn", ":normal aν<Esc>", desc = "Insert ν", nowait = true, remap = false },
    { "<leader>Sgo", ":normal aο<Esc>", desc = "Insert ο", nowait = true, remap = false },
    { "<leader>Sgp", ":normal aπ<Esc>", desc = "Insert π", nowait = true, remap = false },
    { "<leader>Sgr", ":normal aρ<Esc>", desc = "Insert ρ", nowait = true, remap = false },
    { "<leader>Sgs", ":normal aσ<Esc>", desc = "Insert σ", nowait = true, remap = false },
    { "<leader>Sgt", ":normal aθ<Esc>", desc = "Insert θ", nowait = true, remap = false },
    { "<leader>Sgu", ":normal aτ<Esc>", desc = "Insert τ", nowait = true, remap = false },
    { "<leader>Sgv", ":normal aυ<Esc>", desc = "Insert υ", nowait = true, remap = false },
    { "<leader>Sgw", ":normal aω<Esc>", desc = "Insert ω", nowait = true, remap = false },
    { "<leader>Sgx", ":normal aξ<Esc>", desc = "Insert ξ", nowait = true, remap = false },
    { "<leader>Sgy", ":normal aψ<Esc>", desc = "Insert ψ", nowait = true, remap = false },
    { "<leader>Sgz", ":normal aζ<Esc>", desc = "Insert ζ", nowait = true, remap = false },

    { "<leader>Sl", group = "Logical", nowait = true, remap = false },
    { "<leader>Sla", ":normal a∧<Esc>", desc = "Insert ∧", nowait = true, remap = false },
    { "<leader>Sle", ":normal a∈<Esc>", desc = "Insert ∈", nowait = true, remap = false },
    { "<leader>Sln", ":normal a¬<Esc>", desc = "Insert ¬", nowait = true, remap = false },
    { "<leader>Sp", ":normal aπ<Esc>", desc = "Insert π", nowait = true, remap = false },

    { "<leader>Ss", group = "Subscripts", nowait = true, remap = false },
    { "<leader>Ss+", ":normal a₊<Esc>", desc = "Insert subscript +", nowait = true, remap = false },
    { "<leader>Ss-", ":normal a₋<Esc>", desc = "Insert subscript -", nowait = true, remap = false },
    { "<leader>Ss0", ":normal a₀<Esc>", desc = "Insert subscript 0", nowait = true, remap = false },
    { "<leader>Ss1", ":normal a₁<Esc>", desc = "Insert subscript 1", nowait = true, remap = false },
    { "<leader>Ss2", ":normal a₂<Esc>", desc = "Insert subscript 2", nowait = true, remap = false },
    { "<leader>Ss3", ":normal a₃<Esc>", desc = "Insert subscript 3", nowait = true, remap = false },
    { "<leader>Ss4", ":normal a₄<Esc>", desc = "Insert subscript 4", nowait = true, remap = false },
    { "<leader>Ss5", ":normal a₅<Esc>", desc = "Insert subscript 5", nowait = true, remap = false },
    { "<leader>Ss6", ":normal a₆<Esc>", desc = "Insert subscript 6", nowait = true, remap = false },
    { "<leader>Ss7", ":normal a₇<Esc>", desc = "Insert subscript 7", nowait = true, remap = false },
    { "<leader>Ss8", ":normal a₈<Esc>", desc = "Insert subscript 8", nowait = true, remap = false },
    { "<leader>Ss9", ":normal a₉<Esc>", desc = "Insert subscript 9", nowait = true, remap = false },
}
