-- Turn off IndentBlankline for big files
-- vim.api.nvim_create_autocmd("BufEnter", {
--     group = vim.api.nvim_create_augroup("IndentBlanklineBigFile", {}),
--     pattern = "*",
--     callback = function()
--         if vim.api.nvim_buf_line_count(0) > 1000 then
--             require("indent_blankline.commands").disable()
--         end
--     end,
-- })

-- translate to lua

-- " disable syntax highlighting in big files
-- function DisableSyntaxTreesitter()
--     echo("Big file, disabling syntax, treesitter and folding")
--     if exists(':TSBufDisable')
--         exec 'TSBufDisable autotag'
--         exec 'TSBufDisable highlight'
--         " etc...
--     endif
--
--     set foldmethod=manual
--     syntax clear
--     syntax off    " hmmm, which one to use?
--     filetype off
--     set noundofile
--     set noswapfile
--     set noloadplugins
-- endfunction
--
-- augroup BigFileDisable
--     autocmd!
--     " autocmd BufWinEnter * if getfsize(expand("%")) > 512 * 1024 | exec DisableSyntaxTreesitter() | endif
--     autocmd BufReadPre,FileReadPre * if getfsize(expand("%")) > 512 * 1024 | exec DisableSyntaxTreesitter() | endif
--
-- augroup END
--
